### ISSUE TITLE
Error Unknown mod

### ISSUE THREAD

**Issue by djzlorb** [youdz/d2-stash-organizer#26] opened 2021-08-30 15:17 UTC
Error for open my cheracter:
For d2x - Failed to parse Corpsemourn at row 0, column 2: Unknown mod 304 on page 1
For sss - Failed to parse Felloak at row 7, column 8: Unknown mod 265 on page 1

[Save.zip](https://github.com/youdz/d2-stash-organizer/files/7077704/Save.zip)

**Comment by youdz** [comment] 2021-09-04 15:17
Both open correctly when I try your save files:

<img width="605" alt="Screen Shot 2021-09-04 at 11 15 53" src="https://user-images.githubusercontent.com/4647197/132099402-31abddcd-b92a-4889-a578-d3b12158c1ed.png">
<img width="611" alt="Screen Shot 2021-09-04 at 11 16 15" src="https://user-images.githubusercontent.com/4647197/132099403-9c3dc010-635a-4f11-9587-1f7606010a66.png">

Can you elaborate on how you're getting the error? Are you using https://youdz.github.io/d2-stash-organizer/ or some alternative version?

**Comment by youdz** [comment] 2021-09-25 14:46
Closing since I can't reproduce and got no clarification.

**Closed by youdz** 2021-09-25 14:46 UTC
