### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by pmduguay** [youdz/d2-stash-organizer#3] opened 2021-06-06 01:19 UTC
While trying to upload my shared stash, I get this error: Cannot read property 'name' of undefined.

Name of the stash: _LOD_SharedStashSave.sss
Version of PlugY: PlugY_The_Survival_Kit_v14.02

I run it on my mac through Porting kit + Wine, and can't directly access my D2files (to access it, I need to click "show package contents" and that's not an option when I try to find my file from your upload button) so I tried to open the Stash from my backup that is on my mac, so that must be why it isn't working.

Or maybe not?

**Comment by youdz** [comment] 2021-06-06 14:21
Can you post your stash save file somewhere so I can give it a try?

Regarding the .app bundle on Mac, what I would do is go to the save file in regular Finder (with "show package contents"), copy the save file to **somewhere outside of the app bundle**, and then upload that to the tool. Then when downloading, do the same thing in reverse: show package contents, go to the save file, and replace with the new one.
It takes a minute, but that way you can use your latest save file directly.

**Comment by pmduguay** [comment] 2021-06-06 18:24
That is exactly what I was planning to do!

Here's the file: https://www.dropbox.com/s/ffxxxnwexdy39vq/_LOD_SharedStashSave.sss?dl=0

Oh, by the way, I didn't mention that my personal stash files are working.

**Comment by pmduguay** [comment] 2021-06-15 02:01
Hey have you come around to see the problem? I just got a new PC and I still get the same error.

**Comment by Ganguedes** [comment] 2021-06-18 14:46
As Cain would say: Good Day!

So, a friend os mine send me the link to keep track for a holy grail, but i was getting the same error as pmduguay said. I had a lot of itens already and on my character's personal stash, it was working perfectly. And then it hit me. PlugY keeps backup files after every time you quit and save. On my oldest files of Shared Stash, for my surprise, it worked the way it should. This is the part that gets funny. I manually switched Shared Stash pages with Personal Stash pages from a Bow Amazon, and most of them worked just fine, until this one specific page containing Milabrega's set made the error occur. Isolating the items, i found that the set Kite Shield, Milabrega's Orb, when present on either files, Shared OR Personal stash, was making the error occur.

Maybe i was just lucky, i don't understand nothing about codes, programming or languages like JavaScript or whatever, but this made it happen here.

I hope this helped!

And don't forget. Stay a while and lisent. xD

**Comment by pmduguay** [comment] 2021-06-18 15:07
I have that set, but it still doesn't work if I take it out of the shared stash. More than that, the personal stash still works if I have the set in it aswell.

**Comment by Ganguedes** [comment] 2021-06-18 17:35
I'm sorry to hear that.

But i think you're missing the point here. I didn't said that Milabrega's Orb was THE problem, but that was MY problem. I guess it could happen to other items or at least this case is leadin me to this conclusion. It was a process isolating items wich i tought could pay off and it did. Maybe you should do that too,  toggle pages from Shared to Personal stash, and find what is cousing this problem.

I know it sounds...laborious, but it's way easier than doing item by item organization.

Again, i hope it was helpful.

**Comment by youdz** [comment] 2021-06-19 13:23
I found time to look at your save file, and the issue is with the Delirium in a Demonhead on page 12. Somehow it's pointing to a runeword that doesn't exist.

I'm looking at why it's broken right now, and will update this issue as soon as I found the root cause. In the meantime, to avoid similar issues in the future I'm putting clear error messages in place. In this case, instead of `Cannot read property 'name' of undefined`, you'll get `Failed to parse Demonhead at row 0, column 4 on page 12`.


On the "time to response" part, I'm going to post here in case someone else swings by at some point. I'm sorry it took me so long to get to it, I have _very_ limited free time to work on this project, so fixes and new features are not going to follow any kind of regular schedule. Sometimes I'll spend a full week-end working on it and ship 6 fixes and 4 new features. Sometimes it'll be completely silent for 3 weeks. I realize that's not what most people want to hear, and I apologize for that.

I'm in it for the long run, I even want this project to be usable with D2R in September if I PlugY is compatible and I can manage it, so I need to not burn out by working nights on this in addition to my actual job. Please bear with me for a bit. 😄

**Comment by Tiegerkatzi** [comment] 2021-06-19 14:22
Hello,

if you need more data I have the same error. Thanks for this nice project.

Windows7
d2 1.14D
Plugy 14.02

https://www.dropbox.com/s/onux1172a4ofjn7/_LOD_SharedStashSave.sss?dl=0

**Comment by youdz** [comment] 2021-06-19 14:32
There you go, Delirium fixed, the app is now working for the stash linked by @pmduguay.

I'm closing this issue, @Tiegerkatzi you have a completely unreadable item at row 2, column 8 on page 1, that's a different issue. Now with clearer error messages, people should be able to find the problematic item easily every time. If it's a legit item, then feel free to open a new issue so I can fix it separately. 👍

**Closed by youdz** 2021-06-19 14:32 UTC

**Comment by pmduguay** [comment] 2021-06-20 03:00
It works, thanks a ton!
