### ISSUE TITLE
Add README (formerly: Brief usage explanation possible?)

### ISSUE THREAD

**Issue by sthag** [youdz/d2-stash-organizer#5] opened 2021-07-17 08:43 UTC
Hello,

I hope it is ok to use this issue to ask for a brief explanation how to use the tool.
I stumbled upon this while searching for tools to show stashes to friends.

I'm not really into all the code and modules used and only have a basic understanding of nodejs.
~~So sadly I could not fully get it to work.~~ I think I'm missing something.
Edit: I also just now found the GitHub pages with the live site. So I guess this whole issue is not needed.

So far I tried (using nodesjs lts v14.17.0):

* running the site via `npx http-server` inside of `/src/web/` which results in the following error from the browser:

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec. [App.tsx]

* executing `npm install`, placing a stash file at `test/stash.sss` and running `npm run-script start` which gives a list of items on the console like:

> Chipped Topaz undefined
> ...

* running `npm run-script build` which starts to process files inside `src/` and stops with an error:

> [!] Error: Cannot find module 'rollup-plugin-filesize'
> Require stack:
> - /mnt/d/d2-stash-organizer-main/node_modules/rollup-plugin-summary/index.js
> - /mnt/d/d2-stash-organizer-main/rollup.config.js
> - /mnt/d/d2-stash-organizer-main/node_modules/rollup/dist/shared/loadConfigFile.js
> - /mnt/d/d2-stash-organizer-main/node_modules/rollup/dist/bin/rollup
> ...
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! stash-organizer@1.0.0 build: `npm run format && npm run lint && rm -r ./docs && rollup -c --environment PROD`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the stash-organizer@1.0.0 build script.

* Installed the missing module via `npm install rollup-plugin-filesize` and again ran `npm run-script build` which results in:

> rm: cannot remove './docs': No such file or directory
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! stash-organizer@1.0.0 build: `npm run format && npm run lint && rm -r ./docs && rollup -c --environment PROD`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the stash-organizer@1.0.0 build script.

* Created the `/docs/` folder ... got error for missing module `postcss`, installed and again ran `npm run-script build`:

> src/web/index.html → docs...
> 
> 📄 Generated files:
> 
> Name                   Size       Minified   Gzipped   Brotli
> -----------------------------------------------------------------
> App-c1e34e98.js        49.48 KB   49.43 KB   17.38 KB  15.56 KB
> game-data-cd564084.js  395.37 KB  395.37 KB  55.01 KB  44.96 KB
> ---------------------  ---------  --------   --------  ----------
> Total                  444.85 KB  444.8 KB   72.39 KB  60.52 KB
> 
> created docs in 42.7s

* Now ran `npx http-server -o --cors` and now am able to run the site. But I'm not sure if it is correct like this.

Thanks
Stephan

**Comment by youdz** [comment] 2021-07-17 13:39
Well, the answer is simpler than you think. I really need to write a README for people who find this through GitHub.

This is a web tool, it's hosted on https://youdz.github.io/d2-stash-organizer/

That's it, no need to pull, fork or try and run it locally. The node part is just here to help me debug or test more complex scripts. Note that there is a major refactor happening on the project right now (I finally have the code needed to display mods exactly like in game), so the web version was generated a few commits ago.

**Comment by sthag** [comment] 2021-07-17 15:48
Thank you for your reply. The tool is great. I saw the refactor notes in the latest commit and am really curious.

**Comment by Tmkrth** [comment] 2021-07-18 14:45
> (I finally have the code needed to display mods exactly like in game)

This is fantastic!

**Comment by ChaosMarc** [comment] 2021-07-19 18:39
> That's it, no need to pull, fork or try and run it locally.

@youdz But what if someone would want to do that? I for myself, would love to offer some help but couldn't get it to build locally. Also there are people who like to host stuff like this for themselves for privacy reasons or offline usability. So I would be very happy if you would add the steps to actually build this project to the README :)

How do you stand on making the sorting configurable? I don't know if you know this project https://github.com/youdz/d2-stash-organizer which had this configurable to some degree, but the creator removed it for simplicity reasons later on. I forked it and made everything regarding the sorting configurable because I think everyone has a different taste on how a huge stash should be organized.

**Comment by sthag** [comment] 2021-07-19 19:04
@ChaosMarc The link you mention is the exact same project we are in right now :)

**Comment by ChaosMarc** [comment] 2021-07-19 19:06
https://github.com/mrpara/d2_plugy_stash_organizer

Sorry I must have copied the wrong tab's url 😅

**Comment by youdz** [comment] 2021-07-20 12:11
Oh yes, don't get me wrong. As I said I'm worried a potentially missing dependency, because build reproducibility is critical. Otherwise this wouldn't be an open-source project. README is definitely on my TODO list, I just haven't had time to work on this project in the past 3 weeks. Long story short for development is that:
- `npm install` pulls dependency from NPM.
- `npm run watch ` runs the project in watch mode on http://localhost:10001.

There are a couple other scripts that you most likely won't need, like:
- `npm run game-strings` re-generates the JSON containing all game texts, useful if you want to port this tool in a different language and have access to the game's string files.
- `npm run game-data` re-generates the JSON-format game data (depends on game strings), mostly ran if you want to pull more data than I currently do from the game .tbl files.
- `npm run start` runs `src/scripts/main.ts` in node, which is a messy playground I use for debugging and will never trigger the same thing, so don't run it unless you modified [main.t](https://github.com/youdz/d2-stash-organizer/blob/main/src/scripts/main.ts)s for your use case.


As a temporary workaround if anyone wants to host it somewhere private they can access offline, all you need to host is the `docs/` folder. That's what is being served on https://youdz.github.io/d2-stash-organizer/. It is generated by running `npm run build` on the project. Right now though, it [hasn't been re-generated since the refactor](https://github.com/youdz/d2-stash-organizer/commit/4e45618fddd675cb24842f5d65578f4521f2c925) so it'll look quite off if you run this on latest. This is a small pet project that isn't and probably won't ever be full CI/CD, so this step is what lets me trigger "releases". 

>How do you stand on making the sorting configurable?

It's complicated. 😅 Here is my position: the goal of this tool is to be **a solution for people who don't know how to code**. I am not interested in providing a command-line tool for PlugY stash sorting, because in this case there were much better-suited languages for it than Typescript, and better Node support for binary streams than the super-simplistic UInt8Arrays I have to use in the browser.

In other words, I do not want to grow a command-line API with options that are not available in the web UI. Which means if the goal is to make grail sections reorderable for instance, the complexity becomes building a UI that allows this reordering (quite harder than receiving a list of string through an API parameter). The good news is that I built things like [the order of unique items](https://github.com/youdz/d2-stash-organizer/blob/main/src/scripts/grail/list/uniquesOrder.ts) as plain JSON models, so that they can become dynamic with no change to the organization logic in the future. It's just quite low on my list of priorities.

Note that you'd be surprised how few people are strongly opinionated about how a large stash should be organized. Most people I talked to, and most reactions on reddit, just want some order. As long as everything is accessible in a few clicks through indices, it doesn't really matter to them if sets are before or after uniques. As someone who is big on UX, I constantly try to balance the complexity of a customization UI with the value it does provide to users. A crazy configuration panel for something most users only consider "nice to have" is on the wrong side of that balance, which brings us to my initial answer: it's complicated. 😛 

PS: I really need to say thank you for PlugY, I've been using it on and off for years and don't have anything bad to say about it. 😁 If I had the courage to build this with in-game UI controls in C to enhance PlugY directly, I would. But that's just not realistic for me right now.

**Comment by ChaosMarc** [comment] 2021-07-20 16:48
> Oh yes, don't get me wrong. As I said I'm worried about a potentially missing dependency, because build reproducibility is critical. Otherwise this wouldn't be an open-source project. README is definitely on my TODO list, I just haven't had time to work on this project in the past 3 weeks. 

Good to hear :) I was a bit shocked by your previous answer :D

>Long story short for development is that:
> 
> * `npm install` pulls dependency from NPM.
> * `npm run watch` runs the project in watch mode on http://localhost:10001.
> 

Thanks. This worked perfectly :)

> It's complicated. 😅 Here is my position: the goal of this tool is to be **a solution for people who don't know how to code**. I am not interested in providing a command-line tool for PlugY stash sorting, because in this case there were much better-suited languages for it than Typescript, and better Node support for binary streams than the super-simplistic UInt8Arrays I have to use in the browser.

I totally agree. This project shouldn't try to integrate with PlugY or offer a CLI. It's a web based standalone and that's it. I've thought about a real integration into PlugY written in C++ quite often. An ingame "sort" and "search" button would be awesome, but this is way beyond my paygrade 👼 

> In other words, I do not want to grow a command-line API with options that are not available in the web UI. Which means if the goal is to make grail sections reorderable for instance, the complexity becomes building a UI that allows this reordering (quite harder than receiving a list of string through an API parameter). The good news is that I built things like [the order of unique items](https://github.com/youdz/d2-stash-organizer/blob/main/src/scripts/grail/list/uniquesOrder.ts?rgh-link-date=2021-07-20T12%3A11%3A56Z) as plain JSON models, so that they can become dynamic with no change to the organization logic in the future. It's just quite low on my list of priorities.

I also agree that building a UI which allows detailed sorting customizations will be a big challenge. I had my problems with just allowing it via ini parameter for the python tool without overcomplicating everything to a point where the users have to read a page long manual. Good thing you made everything with expandability in mind! Not many developers actually do this for their pet projects 👍 


> Note that you'd be surprised how few people are strongly opinionated about how a large stash should be organized. Most people I talked to, and most reactions on reddit, just want some order. As long as everything is accessible in a few clicks through indices, it doesn't really matter to them if sets are before or after uniques.

Maybe you're right and I'm just pedantic 🤣 Just to give you an example: I usually have every single unique on it's separate page (sorted by ethereal status and ideally by perfectness). I like to change the sorting order of the unique pages sometimes depending on what I need at the moment (required level, name or item type like your default sorting)

> As someone who is big on UX, I constantly try to balance the complexity of a customization UI with the value it does provide to users. A crazy configuration panel for something most users only consider "nice to have" is on the wrong side of that balance, which brings us to my initial answer: it's complicated. 😛

But would you be open to pull requests with more and more configurations (with UX in mind of course). Those could be hidden behind an "advanced" toggle or something.

> PS: I really need to say thank you for PlugY, I've been using it on and off for years and don't have anything bad to say about it. 😁 If I had the courage to build this with in-game UI controls in C to enhance PlugY directly, I would. But that's just not realistic for me right now.

I'm not the creator of PlugY. This would be Yohann. I just manage his source code on Github (with his permission). Before new official releases I relay the feedback and improvements to him so that he can include them in his local code.

**Comment by youdz** [comment] 2021-07-24 13:19
There you go, found some quiet time this morning, I added a clean README.

>But would you be open to pull requests with more and more configurations (with UX in mind of course). Those could be hidden behind an "advanced" toggle or something.

Absolutely. The current refactor in progress moves the organization parameters to their own page, specifically to give them some room to grow. For smaller configurations that just need a couple checkboxes or a new number input, I'm absolutely open to direct PRs. For larger configurations, I would recommend being safe and submitting a feature request first so we can discuss it, because I'd hate to see anyone work hard on a feature and it not being merged.

Note that I'm also big on accessibility. It's obviously not perfect right now, but I will have a high bar when it comes to drag-and-drop features for instance, they will need an equivalent keyboard behavior and proper screen reader support. Even D2R will do it, so the least we can do is also support these players. 🙂

**Closed by youdz** 2021-07-24 13:19 UTC
